# CAR_TYPE -> 세단 SUV 승합차 트럭 리무진
# options -> 주차감지센서', '스마트키', '네비게이션', '통풍시트', '열선시트', '후방카메라', '가
SELECT DISTINCT(A.CAR_ID), A.CAR_TYPE, TRUNCATE(30*(A.DAILY_FEE *((100 - C.DISCOUNT_RATE ) / 100)),0) AS "FEE"
FROM CAR_RENTAL_COMPANY_CAR AS A
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B ON A.CAR_ID = B.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS C ON A.CAR_TYPE = C.CAR_TYPE
WHERE A.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-12-01'
) AND C.DURATION_TYPE LIKE "30%"
GROUP BY A.CAR_ID
HAVING A.CAR_TYPE IN ('세단', 'SUV') AND (FEE >= 500000 AND FEE < 2000000)
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC
