SELECT F.USER_ID, F.NICKNAME, SUM(B.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS B
INNER JOIN USED_GOODS_USER AS F ON B.WRITER_ID = F.USER_ID
WHERE B.STATUS = "DONE"
GROUP BY USER_ID
HAVING SUM(B.PRICE) >= "700000"
ORDER BY SUM(B.PRICE) ASC
