SELECT SUM(GR.SCORE) AS SCORE, EP.EMP_NO, EP.EMP_NAME, EP.POSITION, EP.EMAIL
FROM HR_EMPLOYEES AS EP
JOIN HR_GRADE AS GR ON GR.EMP_NO = EP.EMP_NO
WHERE GR.YEAR = "2022"
GROUP BY EMP_NO
ORDER BY SCORE DESC
LIMIT 1